### ISSUE TITLE
Random error spam, resulting in server crash.

### ISSUE THREAD

**Issue by Ve6om** [RockinChaos/ItemJoin#385]
**Describe the bug**
- Error spams randomly (sometimes a few hours in, or days), resulting in server crash.

**To Reproduce**
- Leave server running.

**Expected behavior**
- Server not crashing.

**Screenshots**
- N/A

**Pastebin**
- https://paste.gg/p/anonymous/f52449658d264e808956dc5969c43bb5

**Please complete the following information:**
 - Resource Version and Build Number: ItemJoin-5.2.2-SNAPSHOT-b694
 - Server Version: Tuinity-"d3ee222" (MC: 1.16.5)

**Additional context**
- Server is a hub server, so it's not automatically restarted. (The crash / error usually happens after a day or so.)

**Comment by RockinChaos** [comment]
Sorry that you are having issues, so the error provided seems to be an older error (not when it originally popped up) so it doesn't contain any information for me to locate the issue as it just shows a generic java error.

I recall seeing this before and I suspect it is already fixed in the latest snapshot.
I recommend updating and letting me know if this changes;
Link: https://ci.craftationgaming.com/job/ItemJoin/700/
**Remember to remove your old ItemJoin.jar file**


- If the issue continues after the snapshot, please provide the following;
- Items.yml
- Config.yml
- Your server log file for that day (this can be sent directly to me instead of posted here if you want). I need this so I can locate the original error message prior to is converting it to a generic java error.
- Crash report? There should have been a crash report generated when this occurred found in a folder called `crash-reports`.

**Comment by Ve6om** [comment]
Seems to be fixed in the latest dev build. I'll open this again, if I encounter it. Thank you!

**Comment by Ve6om** [comment]
Turns out it's not fixed. Happened after about 7 days of running. No crash report was generated. I have emailed you the log.

Items.yml:
https://paste.gg/p/anonymous/3e99c44efc5a4e73817d0dc3e33cc73b

Config.yml:
https://paste.gg/p/anonymous/cfdc1b7ec3c44de7b2ce57ca2f88fef7

**Comment by RockinChaos** [comment]
Got the log looking into this now.

**Comment by RockinChaos** [comment]
So it seems there is some missing information in the logged errors. Can you confirm if `Debugging` is set to true in your config.yml and if it is not, can you enable it please and watch your console logs for errors?

If it is already enabled please let me know.

**Comment by RockinChaos** [comment]
So the latest snapshot contains some major fixes towards similar crash reports as yours so I am 99% sure this is now resolved in the latest snapshot.

Let me know!~

Link: https://ci.craftationgaming.com/job/ItemJoin/706/
**Remember to remove your old ItemJoin.jar file**

**Comment by RockinChaos** [comment]
This bug has been officially fixed in the release of ItemJoin v5.2.2.
You can grab it here; https://www.spigotmc.org/resources/itemjoin.12661/download?version=403809

Please read the changelog as the documentation has not been updated yet;
https://github.com/RockinChaos/ItemJoin/wiki/Recent-Changes
